package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AboutProductLanguage generated by hbm2java
 */
@Entity
@Table(name = "about_product_language", catalog = "drnineni_paint_shop")
public class AboutProductLanguage implements java.io.Serializable {

	private AboutProductLanguageId id;
	private Language language;
	private Product product;
	private String aboutDesc;

	public AboutProductLanguage() {
	}

	public AboutProductLanguage(AboutProductLanguageId id, Language language, Product product, String aboutDesc) {
		this.id = id;
		this.language = language;
		this.product = product;
		this.aboutDesc = aboutDesc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public AboutProductLanguageId getId() {
		return this.id;
	}

	public void setId(AboutProductLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "about_desc", nullable = false, length = 1500)
	public String getAboutDesc() {
		return this.aboutDesc;
	}

	public void setAboutDesc(String aboutDesc) {
		this.aboutDesc = aboutDesc;
	}

}
