package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdminStatus generated by hbm2java
 */
@Entity
@Table(name = "admin_status", catalog = "drnineni_paint_shop")
public class AdminStatus implements java.io.Serializable {

	private Integer adminStatusId;
	private String statusName;
	private String statusDesc;
	private Set<Admin> admins = new HashSet<Admin>(0);

	public AdminStatus() {
	}

	public AdminStatus(String statusName) {
		this.statusName = statusName;
	}

	public AdminStatus(String statusName, String statusDesc, Set<Admin> admins) {
		this.statusName = statusName;
		this.statusDesc = statusDesc;
		this.admins = admins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "admin_status_id", unique = true, nullable = false)
	public Integer getAdminStatusId() {
		return this.adminStatusId;
	}

	public void setAdminStatusId(Integer adminStatusId) {
		this.adminStatusId = adminStatusId;
	}

	@Column(name = "status_name", nullable = false, length = 300)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "status_desc", length = 1500)
	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminStatus")
	public Set<Admin> getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set<Admin> admins) {
		this.admins = admins;
	}

}
