package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "drnineni_paint_shop")
public class Color implements java.io.Serializable {

	private Integer colorId;
	private ColorGroup colorGroup;
	private String htmlColorCode;
	private String colorName;
	private String colorNumber;
	private String description;
	private Set<ProductOrder> productOrders = new HashSet<ProductOrder>(0);

	public Color() {
	}

	public Color(ColorGroup colorGroup, String htmlColorCode, String colorName, String colorNumber) {
		this.colorGroup = colorGroup;
		this.htmlColorCode = htmlColorCode;
		this.colorName = colorName;
		this.colorNumber = colorNumber;
	}

	public Color(ColorGroup colorGroup, String htmlColorCode, String colorName, String colorNumber, String description,
			Set<ProductOrder> productOrders) {
		this.colorGroup = colorGroup;
		this.htmlColorCode = htmlColorCode;
		this.colorName = colorName;
		this.colorNumber = colorNumber;
		this.description = description;
		this.productOrders = productOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "color_id", unique = true, nullable = false)
	public Integer getColorId() {
		return this.colorId;
	}

	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "color_group_id", nullable = false)
	public ColorGroup getColorGroup() {
		return this.colorGroup;
	}

	public void setColorGroup(ColorGroup colorGroup) {
		this.colorGroup = colorGroup;
	}

	@Column(name = "html_color_code", nullable = false, length = 100)
	public String getHtmlColorCode() {
		return this.htmlColorCode;
	}

	public void setHtmlColorCode(String htmlColorCode) {
		this.htmlColorCode = htmlColorCode;
	}

	@Column(name = "color_name", nullable = false, length = 200)
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@Column(name = "color_number", nullable = false, length = 100)
	public String getColorNumber() {
		return this.colorNumber;
	}

	public void setColorNumber(String colorNumber) {
		this.colorNumber = colorNumber;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<ProductOrder> getProductOrders() {
		return this.productOrders;
	}

	public void setProductOrders(Set<ProductOrder> productOrders) {
		this.productOrders = productOrders;
	}

}
