package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ColorGroup generated by hbm2java
 */
@Entity
@Table(name = "color_group", catalog = "drnineni_paint_shop")
public class ColorGroup implements java.io.Serializable {

	private Integer colorGroupId;
	private String name;
	private String htmlColorCode;
	private String colorNumber;
	private String colorName;
	private String description;
	private Set<Color> colors = new HashSet<Color>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public ColorGroup() {
	}

	public ColorGroup(String name, String htmlColorCode, String colorNumber, String colorName) {
		this.name = name;
		this.htmlColorCode = htmlColorCode;
		this.colorNumber = colorNumber;
		this.colorName = colorName;
	}

	public ColorGroup(String name, String htmlColorCode, String colorNumber, String colorName, String description,
			Set<Color> colors, Set<Product> products) {
		this.name = name;
		this.htmlColorCode = htmlColorCode;
		this.colorNumber = colorNumber;
		this.colorName = colorName;
		this.description = description;
		this.colors = colors;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "color_group_id", unique = true, nullable = false)
	public Integer getColorGroupId() {
		return this.colorGroupId;
	}

	public void setColorGroupId(Integer colorGroupId) {
		this.colorGroupId = colorGroupId;
	}

	@Column(name = "name", nullable = false, length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "html_color_code", nullable = false, length = 100)
	public String getHtmlColorCode() {
		return this.htmlColorCode;
	}

	public void setHtmlColorCode(String htmlColorCode) {
		this.htmlColorCode = htmlColorCode;
	}

	@Column(name = "color_number", nullable = false, length = 100)
	public String getColorNumber() {
		return this.colorNumber;
	}

	public void setColorNumber(String colorNumber) {
		this.colorNumber = colorNumber;
	}

	@Column(name = "color_name", nullable = false, length = 100)
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "colorGroup")
	public Set<Color> getColors() {
		return this.colors;
	}

	public void setColors(Set<Color> colors) {
		this.colors = colors;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "colorGroups")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
