package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryType generated by hbm2java
 */
@Entity
@Table(name = "delivery_type", catalog = "drnineni_paint_shop")
public class DeliveryType implements java.io.Serializable {

	private Integer deliveryTypeId;
	private String name;
	private Set<OrderForm> orderForms = new HashSet<OrderForm>(0);

	public DeliveryType() {
	}

	public DeliveryType(String name) {
		this.name = name;
	}

	public DeliveryType(String name, Set<OrderForm> orderForms) {
		this.name = name;
		this.orderForms = orderForms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "delivery_type_id", unique = true, nullable = false)
	public Integer getDeliveryTypeId() {
		return this.deliveryTypeId;
	}

	public void setDeliveryTypeId(Integer deliveryTypeId) {
		this.deliveryTypeId = deliveryTypeId;
	}

	@Column(name = "name", nullable = false, length = 1500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryType")
	public Set<OrderForm> getOrderForms() {
		return this.orderForms;
	}

	public void setOrderForms(Set<OrderForm> orderForms) {
		this.orderForms = orderForms;
	}

}
