package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feature generated by hbm2java
 */
@Entity
@Table(name = "feature", catalog = "drnineni_paint_shop")
public class Feature implements java.io.Serializable {

	private Integer featureId;
	private Set<Product> products = new HashSet<Product>(0);
	private Set<FeatureLanguage> featureLanguages = new HashSet<FeatureLanguage>(0);

	public Feature() {
	}

	public Feature(Set<Product> products, Set<FeatureLanguage> featureLanguages) {
		this.products = products;
		this.featureLanguages = featureLanguages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "feature_id", unique = true, nullable = false)
	public Integer getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(Integer featureId) {
		this.featureId = featureId;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "features")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feature")
	public Set<FeatureLanguage> getFeatureLanguages() {
		return this.featureLanguages;
	}

	public void setFeatureLanguages(Set<FeatureLanguage> featureLanguages) {
		this.featureLanguages = featureLanguages;
	}

}
