package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FeatureLanguage generated by hbm2java
 */
@Entity
@Table(name = "feature_language", catalog = "drnineni_paint_shop")
public class FeatureLanguage implements java.io.Serializable {

	private FeatureLanguageId id;
	private Feature feature;
	private Language language;
	private String featureName;

	public FeatureLanguage() {
	}

	public FeatureLanguage(FeatureLanguageId id, Feature feature, Language language, String featureName) {
		this.id = id;
		this.feature = feature;
		this.language = language;
		this.featureName = featureName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "featureId", column = @Column(name = "feature_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public FeatureLanguageId getId() {
		return this.id;
	}

	public void setId(FeatureLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feature_id", nullable = false, insertable = false, updatable = false)
	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "feature_name", nullable = false, length = 1500)
	public String getFeatureName() {
		return this.featureName;
	}

	public void setFeatureName(String featureName) {
		this.featureName = featureName;
	}

}
