package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FeatureLanguageId generated by hbm2java
 */
@Embeddable
public class FeatureLanguageId implements java.io.Serializable {

	private int featureId;
	private int languageId;

	public FeatureLanguageId() {
	}

	public FeatureLanguageId(int featureId, int languageId) {
		this.featureId = featureId;
		this.languageId = languageId;
	}

	@Column(name = "feature_id", nullable = false)
	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FeatureLanguageId))
			return false;
		FeatureLanguageId castOther = (FeatureLanguageId) other;

		return (this.getFeatureId() == castOther.getFeatureId()) && (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFeatureId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
