package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FreeTool generated by hbm2java
 */
@Entity
@Table(name = "free_tool", catalog = "drnineni_paint_shop")
public class FreeTool implements java.io.Serializable {

	private Integer toolId;
	private Set<Product> products = new HashSet<Product>(0);
	private Set<ToolLanguage> toolLanguages = new HashSet<ToolLanguage>(0);

	public FreeTool() {
	}

	public FreeTool(Set<Product> products, Set<ToolLanguage> toolLanguages) {
		this.products = products;
		this.toolLanguages = toolLanguages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tool_id", unique = true, nullable = false)
	public Integer getToolId() {
		return this.toolId;
	}

	public void setToolId(Integer toolId) {
		this.toolId = toolId;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "freeTools")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "freeTool")
	public Set<ToolLanguage> getToolLanguages() {
		return this.toolLanguages;
	}

	public void setToolLanguages(Set<ToolLanguage> toolLanguages) {
		this.toolLanguages = toolLanguages;
	}

}
