package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupLanguage generated by hbm2java
 */
@Entity
@Table(name = "group_language", catalog = "drnineni_paint_shop")
public class GroupLanguage implements java.io.Serializable {

	private GroupLanguageId id;
	private Language language;
	private ProductGroup productGroup;
	private String name;
	private String description;

	public GroupLanguage() {
	}

	public GroupLanguage(GroupLanguageId id, Language language, ProductGroup productGroup, String name) {
		this.id = id;
		this.language = language;
		this.productGroup = productGroup;
		this.name = name;
	}

	public GroupLanguage(GroupLanguageId id, Language language, ProductGroup productGroup, String name,
			String description) {
		this.id = id;
		this.language = language;
		this.productGroup = productGroup;
		this.name = name;
		this.description = description;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productGroupId", column = @Column(name = "product_group_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public GroupLanguageId getId() {
		return this.id;
	}

	public void setId(GroupLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_group_id", nullable = false, insertable = false, updatable = false)
	public ProductGroup getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(ProductGroup productGroup) {
		this.productGroup = productGroup;
	}

	@Column(name = "name", nullable = false, length = 1500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
