package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupLanguageId generated by hbm2java
 */
@Embeddable
public class GroupLanguageId implements java.io.Serializable {

	private int productGroupId;
	private int languageId;

	public GroupLanguageId() {
	}

	public GroupLanguageId(int productGroupId, int languageId) {
		this.productGroupId = productGroupId;
		this.languageId = languageId;
	}

	@Column(name = "product_group_id", nullable = false)
	public int getProductGroupId() {
		return this.productGroupId;
	}

	public void setProductGroupId(int productGroupId) {
		this.productGroupId = productGroupId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupLanguageId))
			return false;
		GroupLanguageId castOther = (GroupLanguageId) other;

		return (this.getProductGroupId() == castOther.getProductGroupId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductGroupId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
