package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GuideLanguage generated by hbm2java
 */
@Entity
@Table(name = "guide_language", catalog = "drnineni_paint_shop")
public class GuideLanguage implements java.io.Serializable {

	private GuideLanguageId id;
	private Guide guide;
	private Language language;
	private String guideType;
	private String guideValue;

	public GuideLanguage() {
	}

	public GuideLanguage(GuideLanguageId id, Guide guide, Language language, String guideType, String guideValue) {
		this.id = id;
		this.guide = guide;
		this.language = language;
		this.guideType = guideType;
		this.guideValue = guideValue;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "guideId", column = @Column(name = "guide_id", nullable = false)) })
	public GuideLanguageId getId() {
		return this.id;
	}

	public void setId(GuideLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guide_id", nullable = false, insertable = false, updatable = false)
	public Guide getGuide() {
		return this.guide;
	}

	public void setGuide(Guide guide) {
		this.guide = guide;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "guide_type", nullable = false, length = 1500)
	public String getGuideType() {
		return this.guideType;
	}

	public void setGuideType(String guideType) {
		this.guideType = guideType;
	}

	@Column(name = "guide_value", nullable = false, length = 1500)
	public String getGuideValue() {
		return this.guideValue;
	}

	public void setGuideValue(String guideValue) {
		this.guideValue = guideValue;
	}

}
