package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuideLanguageId generated by hbm2java
 */
@Embeddable
public class GuideLanguageId implements java.io.Serializable {

	private int languageId;
	private int guideId;

	public GuideLanguageId() {
	}

	public GuideLanguageId(int languageId, int guideId) {
		this.languageId = languageId;
		this.guideId = guideId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "guide_id", nullable = false)
	public int getGuideId() {
		return this.guideId;
	}

	public void setGuideId(int guideId) {
		this.guideId = guideId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuideLanguageId))
			return false;
		GuideLanguageId castOther = (GuideLanguageId) other;

		return (this.getLanguageId() == castOther.getLanguageId()) && (this.getGuideId() == castOther.getGuideId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLanguageId();
		result = 37 * result + this.getGuideId();
		return result;
	}

}
