package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", catalog = "drnineni_paint_shop")
public class Language implements java.io.Serializable {

	private Integer languageId;
	private String name;
	private String code;
	private Set<GroupLanguage> groupLanguages = new HashSet<GroupLanguage>(0);
	private Set<TypeLanguage> typeLanguages = new HashSet<TypeLanguage>(0);
	private Set<GuideLanguage> guideLanguages = new HashSet<GuideLanguage>(0);
	private Set<AboutProductLanguage> aboutProductLanguages = new HashSet<AboutProductLanguage>(0);
	private Set<FeatureLanguage> featureLanguages = new HashSet<FeatureLanguage>(0);
	private Set<ProductTitleLanguage> productTitleLanguages = new HashSet<ProductTitleLanguage>(0);
	private Set<ToolLanguage> toolLanguages = new HashSet<ToolLanguage>(0);

	public Language() {
	}

	public Language(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public Language(String name, String code, Set<GroupLanguage> groupLanguages, Set<TypeLanguage> typeLanguages,
			Set<GuideLanguage> guideLanguages, Set<AboutProductLanguage> aboutProductLanguages,
			Set<FeatureLanguage> featureLanguages, Set<ProductTitleLanguage> productTitleLanguages,
			Set<ToolLanguage> toolLanguages) {
		this.name = name;
		this.code = code;
		this.groupLanguages = groupLanguages;
		this.typeLanguages = typeLanguages;
		this.guideLanguages = guideLanguages;
		this.aboutProductLanguages = aboutProductLanguages;
		this.featureLanguages = featureLanguages;
		this.productTitleLanguages = productTitleLanguages;
		this.toolLanguages = toolLanguages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "language_id", unique = true, nullable = false)
	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<GroupLanguage> getGroupLanguages() {
		return this.groupLanguages;
	}

	public void setGroupLanguages(Set<GroupLanguage> groupLanguages) {
		this.groupLanguages = groupLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<TypeLanguage> getTypeLanguages() {
		return this.typeLanguages;
	}

	public void setTypeLanguages(Set<TypeLanguage> typeLanguages) {
		this.typeLanguages = typeLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<GuideLanguage> getGuideLanguages() {
		return this.guideLanguages;
	}

	public void setGuideLanguages(Set<GuideLanguage> guideLanguages) {
		this.guideLanguages = guideLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<AboutProductLanguage> getAboutProductLanguages() {
		return this.aboutProductLanguages;
	}

	public void setAboutProductLanguages(Set<AboutProductLanguage> aboutProductLanguages) {
		this.aboutProductLanguages = aboutProductLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<FeatureLanguage> getFeatureLanguages() {
		return this.featureLanguages;
	}

	public void setFeatureLanguages(Set<FeatureLanguage> featureLanguages) {
		this.featureLanguages = featureLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ProductTitleLanguage> getProductTitleLanguages() {
		return this.productTitleLanguages;
	}

	public void setProductTitleLanguages(Set<ProductTitleLanguage> productTitleLanguages) {
		this.productTitleLanguages = productTitleLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ToolLanguage> getToolLanguages() {
		return this.toolLanguages;
	}

	public void setToolLanguages(Set<ToolLanguage> toolLanguages) {
		this.toolLanguages = toolLanguages;
	}

}
