package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Litreage generated by hbm2java
 */
@Entity
@Table(name = "litreage", catalog = "drnineni_paint_shop")
public class Litreage implements java.io.Serializable {

	private Integer litreageId;
	private Product product;
	private QtyUnit qtyUnit;
	private int qty;
	private double unitPrice;
	private String description;
	private Set<ProductOrder> productOrders = new HashSet<ProductOrder>(0);

	public Litreage() {
	}

	public Litreage(Product product, QtyUnit qtyUnit, int qty, double unitPrice) {
		this.product = product;
		this.qtyUnit = qtyUnit;
		this.qty = qty;
		this.unitPrice = unitPrice;
	}

	public Litreage(Product product, QtyUnit qtyUnit, int qty, double unitPrice, String description,
			Set<ProductOrder> productOrders) {
		this.product = product;
		this.qtyUnit = qtyUnit;
		this.qty = qty;
		this.unitPrice = unitPrice;
		this.description = description;
		this.productOrders = productOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "litreage_id", unique = true, nullable = false)
	public Integer getLitreageId() {
		return this.litreageId;
	}

	public void setLitreageId(Integer litreageId) {
		this.litreageId = litreageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "qty_unit_id", nullable = false)
	public QtyUnit getQtyUnit() {
		return this.qtyUnit;
	}

	public void setQtyUnit(QtyUnit qtyUnit) {
		this.qtyUnit = qtyUnit;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	@Column(name = "unit_price", nullable = false, precision = 22, scale = 0)
	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "litreage")
	public Set<ProductOrder> getProductOrders() {
		return this.productOrders;
	}

	public void setProductOrders(Set<ProductOrder> productOrders) {
		this.productOrders = productOrders;
	}

}
