package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "drnineni_paint_shop")
public class Member implements java.io.Serializable {

	private Integer memberId;
	private MemberStatus memberStatus;
	private String name;
	private String phone;
	private String password;
	private String mail;
	private String address;
	private String note;
	private Date createDate;
	private Set<PaymentMethod> paymentMethods = new HashSet<PaymentMethod>(0);
	private Set<OrderForm> orderForms = new HashSet<OrderForm>(0);

	public Member() {
	}

	public Member(MemberStatus memberStatus, String name, String phone, String password, String mail, Date createDate) {
		this.memberStatus = memberStatus;
		this.name = name;
		this.phone = phone;
		this.password = password;
		this.mail = mail;
		this.createDate = createDate;
	}

	public Member(MemberStatus memberStatus, String name, String phone, String password, String mail, String address,
			String note, Date createDate, Set<PaymentMethod> paymentMethods, Set<OrderForm> orderForms) {
		this.memberStatus = memberStatus;
		this.name = name;
		this.phone = phone;
		this.password = password;
		this.mail = mail;
		this.address = address;
		this.note = note;
		this.createDate = createDate;
		this.paymentMethods = paymentMethods;
		this.orderForms = orderForms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "member_id", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_status_id", nullable = false)
	public MemberStatus getMemberStatus() {
		return this.memberStatus;
	}

	public void setMemberStatus(MemberStatus memberStatus) {
		this.memberStatus = memberStatus;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 200)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "password", nullable = false, length = 1000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mail", nullable = false, length = 200)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "address", length = 1500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "note", length = 1000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<PaymentMethod> getPaymentMethods() {
		return this.paymentMethods;
	}

	public void setPaymentMethods(Set<PaymentMethod> paymentMethods) {
		this.paymentMethods = paymentMethods;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<OrderForm> getOrderForms() {
		return this.orderForms;
	}

	public void setOrderForms(Set<OrderForm> orderForms) {
		this.orderForms = orderForms;
	}

}
