package com.coder.model;
// Generated Jan 31, 2021 2:22:28 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OnePayPaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "one_pay_payment_method", catalog = "drnineni_paint_shop")
public class OnePayPaymentMethod implements java.io.Serializable {

	private Integer paymentMethodId;
	private String merchantUserId;
	private String serialId;
	private String channel;
	private String invoiceNo;
	private double amount;
	private String phone;
	private String respCode;
	private String respDesc;
	private String description;
	private String items;
	private Date createDate;

	public OnePayPaymentMethod() {
	}

	public OnePayPaymentMethod(String merchantUserId, String serialId, String channel, String invoiceNo, double amount,
			String phone, String respCode, String respDesc, Date createDate) {
		this.merchantUserId = merchantUserId;
		this.serialId = serialId;
		this.channel = channel;
		this.invoiceNo = invoiceNo;
		this.amount = amount;
		this.phone = phone;
		this.respCode = respCode;
		this.respDesc = respDesc;
		this.createDate = createDate;
	}

	public OnePayPaymentMethod(String merchantUserId, String serialId, String channel, String invoiceNo, double amount,
			String phone, String respCode, String respDesc, String description, String items, Date createDate) {
		this.merchantUserId = merchantUserId;
		this.serialId = serialId;
		this.channel = channel;
		this.invoiceNo = invoiceNo;
		this.amount = amount;
		this.phone = phone;
		this.respCode = respCode;
		this.respDesc = respDesc;
		this.description = description;
		this.items = items;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_method_id", unique = true, nullable = false)
	public Integer getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(Integer paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	@Column(name = "merchant_user_Id", nullable = false, length = 1000)
	public String getMerchantUserId() {
		return this.merchantUserId;
	}

	public void setMerchantUserId(String merchantUserId) {
		this.merchantUserId = merchantUserId;
	}

	@Column(name = "serial_id", nullable = false, length = 1000)
	public String getSerialId() {
		return this.serialId;
	}

	public void setSerialId(String serialId) {
		this.serialId = serialId;
	}

	@Column(name = "channel", nullable = false, length = 300)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "invoice_no", nullable = false, length = 300)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "resp_code", nullable = false, length = 100)
	public String getRespCode() {
		return this.respCode;
	}

	public void setRespCode(String respCode) {
		this.respCode = respCode;
	}

	@Column(name = "resp_desc", nullable = false, length = 300)
	public String getRespDesc() {
		return this.respDesc;
	}

	public void setRespDesc(String respDesc) {
		this.respDesc = respDesc;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "items", length = 1500)
	public String getItems() {
		return this.items;
	}

	public void setItems(String items) {
		this.items = items;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
