package com.coder.model;
// Generated Feb 17, 2021 9:29:04 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "payment_method", catalog = "drnineni_paint_shop")
public class PaymentMethod implements java.io.Serializable {

	private Integer paymentMethodId;
	private String serialId;
	private String channel;
	private Date createDate;
	private String phone;
	private String invoiceNo;
	private String respDesc;
	private String description;
	private String respCode;
	private String merchantUserId;
	private double amount;
	private Set<OrderForm> orderForms = new HashSet<OrderForm>(0);
	private Set<Member> members = new HashSet<Member>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(String serialId, String channel, Date createDate, String phone, String invoiceNo,
			String respDesc, String respCode, String merchantUserId, double amount) {
		this.serialId = serialId;
		this.channel = channel;
		this.createDate = createDate;
		this.phone = phone;
		this.invoiceNo = invoiceNo;
		this.respDesc = respDesc;
		this.respCode = respCode;
		this.merchantUserId = merchantUserId;
		this.amount = amount;
	}

	public PaymentMethod(String serialId, String channel, Date createDate, String phone, String invoiceNo,
			String respDesc, String description, String respCode, String merchantUserId, double amount,
			Set<OrderForm> orderForms, Set<Member> members) {
		this.serialId = serialId;
		this.channel = channel;
		this.createDate = createDate;
		this.phone = phone;
		this.invoiceNo = invoiceNo;
		this.respDesc = respDesc;
		this.description = description;
		this.respCode = respCode;
		this.merchantUserId = merchantUserId;
		this.amount = amount;
		this.orderForms = orderForms;
		this.members = members;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_method_id", unique = true, nullable = false)
	public Integer getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(Integer paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	@Column(name = "serial_id", nullable = false, length = 1500)
	public String getSerialId() {
		return this.serialId;
	}

	public void setSerialId(String serialId) {
		this.serialId = serialId;
	}

	@Column(name = "channel", nullable = false, length = 300)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "invoice_no", nullable = false, length = 300)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "resp_desc", nullable = false, length = 300)
	public String getRespDesc() {
		return this.respDesc;
	}

	public void setRespDesc(String respDesc) {
		this.respDesc = respDesc;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "resp_code", nullable = false, length = 100)
	public String getRespCode() {
		return this.respCode;
	}

	public void setRespCode(String respCode) {
		this.respCode = respCode;
	}

	@Column(name = "merchant_user_id", nullable = false, length = 1000)
	public String getMerchantUserId() {
		return this.merchantUserId;
	}

	public void setMerchantUserId(String merchantUserId) {
		this.merchantUserId = merchantUserId;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	public Set<OrderForm> getOrderForms() {
		return this.orderForms;
	}

	public void setOrderForms(Set<OrderForm> orderForms) {
		this.orderForms = orderForms;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "payment_method_owner", catalog = "drnineni_paint_shop", joinColumns = {
			@JoinColumn(name = "payment_method_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "member_id", nullable = false, updatable = false) })
	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

}
