package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductGuideLanguage generated by hbm2java
 */
@Entity
@Table(name = "product_guide_language", catalog = "drnineni_paint_shop")
public class ProductGuideLanguage implements java.io.Serializable {

	private ProductGuideLanguageId id;

	public ProductGuideLanguage() {
	}

	public ProductGuideLanguage(ProductGuideLanguageId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "guideId", column = @Column(name = "guide_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "guideType", column = @Column(name = "guide_type", nullable = false, length = 1500)),
			@AttributeOverride(name = "guideValue", column = @Column(name = "guide_value", nullable = false, length = 1500)) })
	public ProductGuideLanguageId getId() {
		return this.id;
	}

	public void setId(ProductGuideLanguageId id) {
		this.id = id;
	}

}
