package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductToolLanguage generated by hbm2java
 */
@Entity
@Table(name = "product_tool_language", catalog = "drnineni_paint_shop")
public class ProductToolLanguage implements java.io.Serializable {

	private ProductToolLanguageId id;

	public ProductToolLanguage() {
	}

	public ProductToolLanguage(ProductToolLanguageId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "toolId", column = @Column(name = "tool_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "toolName", column = @Column(name = "tool_name", length = 1500)) })
	public ProductToolLanguageId getId() {
		return this.id;
	}

	public void setId(ProductToolLanguageId id) {
		this.id = id;
	}

}
