package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductMedia generated by hbm2java
 */
@Entity
@Table(name = "product_media", catalog = "drnineni_paint_shop")
public class ProductMedia implements java.io.Serializable {

	private Integer productMediaId;
	private Folder folder;
	private Product product;
	private Date createDate;
	private String mediaType;

	public ProductMedia() {
	}

	public ProductMedia(Folder folder, Product product, Date createDate, String mediaType) {
		this.folder = folder;
		this.product = product;
		this.createDate = createDate;
		this.mediaType = mediaType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_media_id", unique = true, nullable = false)
	public Integer getProductMediaId() {
		return this.productMediaId;
	}

	public void setProductMediaId(Integer productMediaId) {
		this.productMediaId = productMediaId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "folder_id", nullable = false)
	public Folder getFolder() {
		return this.folder;
	}

	public void setFolder(Folder folder) {
		this.folder = folder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "media_type", nullable = false, length = 20)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

}
