package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductGuideLanguageId generated by hbm2java
 */
@Embeddable
public class ProductGuideLanguageId implements java.io.Serializable {

	private int productId;
	private int guideId;
	private int languageId;
	private String guideType;
	private String guideValue;

	public ProductGuideLanguageId() {
	}

	public ProductGuideLanguageId(int productId, int guideId, int languageId, String guideType, String guideValue) {
		this.productId = productId;
		this.guideId = guideId;
		this.languageId = languageId;
		this.guideType = guideType;
		this.guideValue = guideValue;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "guide_id", nullable = false)
	public int getGuideId() {
		return this.guideId;
	}

	public void setGuideId(int guideId) {
		this.guideId = guideId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "guide_type", nullable = false, length = 1500)
	public String getGuideType() {
		return this.guideType;
	}

	public void setGuideType(String guideType) {
		this.guideType = guideType;
	}

	@Column(name = "guide_value", nullable = false, length = 1500)
	public String getGuideValue() {
		return this.guideValue;
	}

	public void setGuideValue(String guideValue) {
		this.guideValue = guideValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductGuideLanguageId))
			return false;
		ProductGuideLanguageId castOther = (ProductGuideLanguageId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getGuideId() == castOther.getGuideId())
				&& (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getGuideType() == castOther.getGuideType()) || (this.getGuideType() != null
						&& castOther.getGuideType() != null && this.getGuideType().equals(castOther.getGuideType())))
				&& ((this.getGuideValue() == castOther.getGuideValue())
						|| (this.getGuideValue() != null && castOther.getGuideValue() != null
								&& this.getGuideValue().equals(castOther.getGuideValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getGuideId();
		result = 37 * result + this.getLanguageId();
		result = 37 * result + (getGuideType() == null ? 0 : this.getGuideType().hashCode());
		result = 37 * result + (getGuideValue() == null ? 0 : this.getGuideValue().hashCode());
		return result;
	}

}
