package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductStatus generated by hbm2java
 */
@Entity
@Table(name = "product_quality", catalog = "drnineni_paint_shop")
public class ProductQuality implements java.io.Serializable {

	private Integer productQualityId;
	private String name;
	private String description;
	private Set<Product> products = new HashSet<Product>(0);

	public ProductQuality() {
	}

	public ProductQuality(String name) {
		this.name = name;
	}

	public ProductQuality(String name, String description, Set<Product> products) {
		this.name = name;
		this.description = description;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_quality_id", unique = true, nullable = false)
	public Integer getProductQualityId() {
		return this.productQualityId;
	}

	public void setProductQualityId(Integer productQualityId) {
		this.productQualityId = productQualityId;
	}

	@Column(name = "name", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productQuality")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
