package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductToolLanguageId generated by hbm2java
 */
@Embeddable
public class ProductToolLanguageId implements java.io.Serializable {

	private int productId;
	private int toolId;
	private int languageId;
	private String toolName;

	public ProductToolLanguageId() {
	}

	public ProductToolLanguageId(int productId, int toolId, int languageId) {
		this.productId = productId;
		this.toolId = toolId;
		this.languageId = languageId;
	}

	public ProductToolLanguageId(int productId, int toolId, int languageId, String toolName) {
		this.productId = productId;
		this.toolId = toolId;
		this.languageId = languageId;
		this.toolName = toolName;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "tool_id", nullable = false)
	public int getToolId() {
		return this.toolId;
	}

	public void setToolId(int toolId) {
		this.toolId = toolId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "tool_name", length = 1500)
	public String getToolName() {
		return this.toolName;
	}

	public void setToolName(String toolName) {
		this.toolName = toolName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductToolLanguageId))
			return false;
		ProductToolLanguageId castOther = (ProductToolLanguageId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getToolId() == castOther.getToolId())
				&& (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getToolName() == castOther.getToolName()) || (this.getToolName() != null
						&& castOther.getToolName() != null && this.getToolName().equals(castOther.getToolName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getToolId();
		result = 37 * result + this.getLanguageId();
		result = 37 * result + (getToolName() == null ? 0 : this.getToolName().hashCode());
		return result;
	}

}
