package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductLiterageQtyunit generated by hbm2java
 */
@Entity
@Table(name = "product_literage_qtyunit", catalog = "drnineni_paint_shop")
public class ProductLiterageQtyunit implements java.io.Serializable {

	private ProductLiterageQtyunitId id;

	public ProductLiterageQtyunit() {
	}

	public ProductLiterageQtyunit(ProductLiterageQtyunitId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "litreageUnitPrice", column = @Column(name = "litreage_unit_price", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "litreageQty", column = @Column(name = "litreage_qty", nullable = false)),
			@AttributeOverride(name = "qtyUnit", column = @Column(name = "qty_unit", nullable = false, length = 400)) })
	public ProductLiterageQtyunitId getId() {
		return this.id;
	}

	public void setId(ProductLiterageQtyunitId id) {
		this.id = id;
	}

}
