package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductTitleLanguage generated by hbm2java
 */
@Entity
@Table(name = "product_title_language", catalog = "drnineni_paint_shop")
public class ProductTitleLanguage implements java.io.Serializable {

	private ProductTitleLanguageId id;
	private Language language;
	private Product product;
	private String name;

	public ProductTitleLanguage() {
	}

	public ProductTitleLanguage(ProductTitleLanguageId id, Language language, Product product, String name) {
		this.id = id;
		this.language = language;
		this.product = product;
		this.name = name;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public ProductTitleLanguageId getId() {
		return this.id;
	}

	public void setId(ProductTitleLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", nullable = false, length = 1500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
