package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name = "product_type", catalog = "drnineni_paint_shop")
public class ProductType implements java.io.Serializable {

	private Integer productTypeId;
	private ProductGroup productGroup;
	private String htmlColorCode;
	private Set<TypeLanguage> typeLanguages = new HashSet<TypeLanguage>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public ProductType() {
	}

	public ProductType(ProductGroup productGroup, String htmlColorCode) {
		this.productGroup = productGroup;
		this.htmlColorCode = htmlColorCode;
	}

	public ProductType(ProductGroup productGroup, String htmlColorCode, Set<TypeLanguage> typeLanguages,
			Set<Product> products) {
		this.productGroup = productGroup;
		this.htmlColorCode = htmlColorCode;
		this.typeLanguages = typeLanguages;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_type_id", unique = true, nullable = false)
	public Integer getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(Integer productTypeId) {
		this.productTypeId = productTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_group_id", nullable = false)
	public ProductGroup getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(ProductGroup productGroup) {
		this.productGroup = productGroup;
	}

	@Column(name = "html_color_code", nullable = false, length = 100)
	public String getHtmlColorCode() {
		return this.htmlColorCode;
	}

	public void setHtmlColorCode(String htmlColorCode) {
		this.htmlColorCode = htmlColorCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productType")
	public Set<TypeLanguage> getTypeLanguages() {
		return this.typeLanguages;
	}

	public void setTypeLanguages(Set<TypeLanguage> typeLanguages) {
		this.typeLanguages = typeLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productType")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
