package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductFeatureLanguageId generated by hbm2java
 */
@Embeddable
public class ProductFeatureLanguageId implements java.io.Serializable {

	private int productId;
	private int featureId;
	private int languageId;
	private String featureName;

	public ProductFeatureLanguageId() {
	}

	public ProductFeatureLanguageId(int productId, int featureId, int languageId, String featureName) {
		this.productId = productId;
		this.featureId = featureId;
		this.languageId = languageId;
		this.featureName = featureName;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "feature_id", nullable = false)
	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "feature_name", nullable = false, length = 1500)
	public String getFeatureName() {
		return this.featureName;
	}

	public void setFeatureName(String featureName) {
		this.featureName = featureName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductFeatureLanguageId))
			return false;
		ProductFeatureLanguageId castOther = (ProductFeatureLanguageId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getFeatureId() == castOther.getFeatureId())
				&& (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getFeatureName() == castOther.getFeatureName())
						|| (this.getFeatureName() != null && castOther.getFeatureName() != null
								&& this.getFeatureName().equals(castOther.getFeatureName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getFeatureId();
		result = 37 * result + this.getLanguageId();
		result = 37 * result + (getFeatureName() == null ? 0 : this.getFeatureName().hashCode());
		return result;
	}

}
