package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductOrder generated by hbm2java
 */
@Entity
@Table(name = "product_order", catalog = "drnineni_paint_shop")
public class ProductOrder implements java.io.Serializable {

	private Integer orderId;
	private Color color;
	private Litreage litreage;
	private OrderForm orderForm;
	private Product product;
	private QtyUnit qtyUnit;
	private int orderQty;

	public ProductOrder() {
	}

	public ProductOrder(Color color, Litreage litreage, OrderForm orderForm, Product product, QtyUnit qtyUnit,
			int orderQty) {
		this.color = color;
		this.litreage = litreage;
		this.orderForm = orderForm;
		this.product = product;
		this.qtyUnit = qtyUnit;
		this.orderQty = orderQty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "color_id", nullable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "litreage_id", nullable = false)
	public Litreage getLitreage() {
		return this.litreage;
	}

	public void setLitreage(Litreage litreage) {
		this.litreage = litreage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_form_id", nullable = false)
	public OrderForm getOrderForm() {
		return this.orderForm;
	}

	public void setOrderForm(OrderForm orderForm) {
		this.orderForm = orderForm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qty_unit_id", nullable = false)
	public QtyUnit getQtyUnit() {
		return this.qtyUnit;
	}

	public void setQtyUnit(QtyUnit qtyUnit) {
		this.qtyUnit = qtyUnit;
	}

	@Column(name = "order_qty", nullable = false)
	public int getOrderQty() {
		return this.orderQty;
	}

	public void setOrderQty(int orderQty) {
		this.orderQty = orderQty;
	}

}
