package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QtyUnit generated by hbm2java
 */
@Entity
@Table(name = "qty_unit", catalog = "drnineni_paint_shop")
public class QtyUnit implements java.io.Serializable {

	private Integer qtyUnitId;
	private String unit;
	private String description;
	private Set<ProductOrder> productOrders = new HashSet<ProductOrder>(0);
	private Set<Litreage> litreages = new HashSet<Litreage>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public QtyUnit() {
	}

	public QtyUnit(String unit, String description) {
		this.unit = unit;
		this.description = description;
	}

	public QtyUnit(String unit, String description, Set<ProductOrder> productOrders, Set<Litreage> litreages,
			Set<Product> products) {
		this.unit = unit;
		this.description = description;
		this.productOrders = productOrders;
		this.litreages = litreages;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qty_unit_id", unique = true, nullable = false)
	public Integer getQtyUnitId() {
		return this.qtyUnitId;
	}

	public void setQtyUnitId(Integer qtyUnitId) {
		this.qtyUnitId = qtyUnitId;
	}

	@Column(name = "unit", nullable = false, length = 400)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qtyUnit")
	public Set<ProductOrder> getProductOrders() {
		return this.productOrders;
	}

	public void setProductOrders(Set<ProductOrder> productOrders) {
		this.productOrders = productOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qtyUnit")
	public Set<Litreage> getLitreages() {
		return this.litreages;
	}

	public void setLitreages(Set<Litreage> litreages) {
		this.litreages = litreages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qtyUnit")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
