package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShopStatus generated by hbm2java
 */
@Entity
@Table(name = "shop_status", catalog = "drnineni_paint_shop")
public class ShopStatus implements java.io.Serializable {

	private Integer statusId;
	private String statusName;
	private String description;
	private Set<Shop> shops = new HashSet<Shop>(0);

	public ShopStatus() {
	}

	public ShopStatus(String statusName, String description) {
		this.statusName = statusName;
		this.description = description;
	}

	public ShopStatus(String statusName, String description, Set<Shop> shops) {
		this.statusName = statusName;
		this.description = description;
		this.shops = shops;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "status_id", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_name", nullable = false, length = 200)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "description", nullable = false, length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopStatus")
	public Set<Shop> getShops() {
		return this.shops;
	}

	public void setShops(Set<Shop> shops) {
		this.shops = shops;
	}

}
