package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name = "shop", catalog = "drnineni_paint_shop")
public class Shop implements java.io.Serializable {

	private Integer shopId;
	private Admin admin;
	private ShopStatus shopStatus;
	private String name;
	private String email;
	private String phone;
	private String address;
	private String description;
	private Date createDate;

	public Shop() {
	}

	public Shop(Admin admin, ShopStatus shopStatus, String name, String email, String phone, String address,
			Date createDate) {
		this.admin = admin;
		this.shopStatus = shopStatus;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.createDate = createDate;
	}

	public Shop(Admin admin, ShopStatus shopStatus, String name, String email, String phone, String address,
			String description, Date createDate) {
		this.admin = admin;
		this.shopStatus = shopStatus;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.description = description;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shop_id", unique = true, nullable = false)
	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "admin_id", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public ShopStatus getShopStatus() {
		return this.shopStatus;
	}

	public void setShopStatus(ShopStatus shopStatus) {
		this.shopStatus = shopStatus;
	}

	@Column(name = "name", nullable = false, length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false, length = 1500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
