package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ToolLanguageId generated by hbm2java
 */
@Embeddable
public class ToolLanguageId implements java.io.Serializable {

	private int languageId;
	private int toolId;

	public ToolLanguageId() {
	}

	public ToolLanguageId(int languageId, int toolId) {
		this.languageId = languageId;
		this.toolId = toolId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "tool_id", nullable = false)
	public int getToolId() {
		return this.toolId;
	}

	public void setToolId(int toolId) {
		this.toolId = toolId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ToolLanguageId))
			return false;
		ToolLanguageId castOther = (ToolLanguageId) other;

		return (this.getLanguageId() == castOther.getLanguageId()) && (this.getToolId() == castOther.getToolId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLanguageId();
		result = 37 * result + this.getToolId();
		return result;
	}

}
