package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TypeLanguageId generated by hbm2java
 */
@Embeddable
public class TypeLanguageId implements java.io.Serializable {

	private int productTypeId;
	private int languageId;

	public TypeLanguageId() {
	}

	public TypeLanguageId(int productTypeId, int languageId) {
		this.productTypeId = productTypeId;
		this.languageId = languageId;
	}

	@Column(name = "product_type_id", nullable = false)
	public int getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypeLanguageId))
			return false;
		TypeLanguageId castOther = (TypeLanguageId) other;

		return (this.getProductTypeId() == castOther.getProductTypeId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductTypeId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
