package com.coder.model;
// Generated Jan 23, 2021 7:50:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeLanguage generated by hbm2java
 */
@Entity
@Table(name = "type_language", catalog = "drnineni_paint_shop")
public class TypeLanguage implements java.io.Serializable {

	private TypeLanguageId id;
	private Language language;
	private ProductType productType;
	private String name;
	private String description;

	public TypeLanguage() {
	}

	public TypeLanguage(TypeLanguageId id, Language language, ProductType productType, String name) {
		this.id = id;
		this.language = language;
		this.productType = productType;
		this.name = name;
	}

	public TypeLanguage(TypeLanguageId id, Language language, ProductType productType, String name,
			String description) {
		this.id = id;
		this.language = language;
		this.productType = productType;
		this.name = name;
		this.description = description;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productTypeId", column = @Column(name = "product_type_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public TypeLanguageId getId() {
		return this.id;
	}

	public void setId(TypeLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_type_id", nullable = false, insertable = false, updatable = false)
	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	@Column(name = "name", nullable = false, length = 3000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
